#!/bin/bash

# Deployment Check Script
# Run this locally to verify your setup before deploying to Render

echo "🔍 Checking deployment readiness..."
echo ""

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
  echo "❌ node_modules not found. Run: npm install"
  exit 1
else
  echo "✅ node_modules exists"
fi

# Check if TypeScript compiles
echo "🔨 Testing TypeScript compilation..."
if npm run build > /dev/null 2>&1; then
  echo "✅ TypeScript compilation successful"
else
  echo "❌ TypeScript compilation failed. Check errors above."
  exit 1
fi

# Check if dist/index.js exists
if [ -f "dist/index.js" ]; then
  echo "✅ dist/index.js exists"
else
  echo "❌ dist/index.js not found after build"
  exit 1
fi

# Check required files
echo "📁 Checking required files..."
files=("package.json" "tsconfig.json" "render.yaml" "schema.sql" "src/index.ts")
for file in "${files[@]}"; do
  if [ -f "$file" ]; then
    echo "✅ $file exists"
  else
    echo "❌ $file is missing"
    exit 1
  fi
done

# Check environment variables (warn only)
echo ""
echo "⚠️  Environment variables check (set these in Render):"
if [ -z "$DATABASE_URL" ]; then
  echo "   ⚠️  DATABASE_URL not set (will be auto-set by Render)"
else
  echo "   ✅ DATABASE_URL is set"
fi

if [ -z "$JWT_SECRET" ]; then
  echo "   ⚠️  JWT_SECRET not set (will be auto-generated by Render)"
else
  echo "   ✅ JWT_SECRET is set"
fi

if [ -z "$PORT" ]; then
  echo "   ⚠️  PORT not set (defaults to 3000, Render will set to 10000)"
else
  echo "   ✅ PORT is set to $PORT"
fi

# Check package.json scripts
echo ""
echo "📜 Checking package.json scripts..."
if grep -q '"start"' package.json; then
  echo "✅ start script found"
else
  echo "❌ start script missing in package.json"
  exit 1
fi

if grep -q '"build"' package.json; then
  echo "✅ build script found"
else
  echo "❌ build script missing in package.json"
  exit 1
fi

# Test start command (dry run)
echo ""
echo "🚀 Testing start command (syntax check only)..."
if node --check dist/index.js > /dev/null 2>&1; then
  echo "✅ dist/index.js syntax is valid"
else
  echo "❌ dist/index.js has syntax errors"
  exit 1
fi

echo ""
echo "✨ All checks passed! Your project is ready for Render deployment."
echo ""
echo "Next steps:"
echo "1. Push your code to GitHub"
echo "2. Go to Render Dashboard → New → Blueprint"
echo "3. Connect your repository"
echo "4. Apply the blueprint"
echo "5. Initialize database schema after database is created"
echo ""
echo "For detailed instructions, see RENDER_DEPLOYMENT.md"
